a = input('Type something: ')
print('The primitive type of this valor is: ', type(a))
print('Have only spaces? ', a.isspace())
print('It is numeric? ', a.isnumeric())
print('It is alphabetic? ', a.isalpha())
print('It is alphanumeric? ', a.isalnum())
print('It is upper? ', a.isupper())
print('It is lower? ', a.islower())
print('It is capitalized? ', a.istitle())